<name>         ::= <letter> | <name-tail>
<name-charset> ::= <letter> | <number> | <mark>
<name-tail>    ::= <name-chareset> <name-tail> | ""

<number>      ::= "-" <ascii-number> <number-tail>
                | <ascii-number> <number-tail>
<number-tail> ::= <ascii-number> <number-tail> | ""

<value> ::= <name> | <number> | "(" <tuple> | "{" <graph>

<tuple>      ::= ")" | <tuple-tail> <tuple>
<tuple-tail> ::= <value> ""
               | <value> ","
               | <value> "<" <tuple-tail>

<graph>      ::= "}" | <name> "=" <graph-tail> <graph>
<graph-tail> ::= <value> ""
               | <value> ";"
               | <value> "<" <graph-tail>

<outer-graph>      ::= <end> | <name> "=" <outer-graph-tail> <outer-graph>
<outer-graph-tail> ::= <value> ""
                     | <value> ";"
                     | <value> "<" <outer-graph-tail>
